### ISSUE TITLE
Doesn't work with Swift

### ISSUE THREAD

**Issue by ilyailya** [AlvaroFranco/AFDropdownNotification#13]
I made a bridging header, imported this lib, and made this code

```
@IBAction func notificationTest(sender: AnyObject) {

    var notification = AFDropdownNotification()
    notification.notificationDelegate = self
    notification.titleText = "Update available";
    notification.subtitleText = "Do you want to download the update of this file?";
    notification.topButtonText = "Accept";
    notification.bottomButtonText = "Cancel";
    notification.dismissOnTap = true;
    notification.image = nil
    notification.presentInView(self.view, withGravityAnimation: true)
    NSLog(notification.description)
}
```

and nothing happens then i click button

**Comment by cloudjanak** [comment]
//notification.notificationDelegate = self
                notification.titleText = "Update available";
                notification.subtitleText = "Do you want to download the update of this file?";
                notification.topButtonText = "Accept";
                notification.bottomButtonText = "Cancel";
                notification.dismissOnTap = true;
                notification.image = UIImage(named: "mainLogo")
                notification.presentInView(self.view, withGravityAnimation: true)
                NSLog(notification.description)

```
            notification.listenEventsWithBlock({ (event : AFDropdownNotificationEvent) -> Void in
                switch (event) {
                case AFDropdownNotificationEvent.TopButton:
                    // Top button
                    break;

                case AFDropdownNotificationEvent.BottomButton:
                    // Bottom button
                    break;

                case AFDropdownNotificationEvent.Tap:
                    // Tap
                    break;

                default:
                    break;
                }
            })
```

this is working fine i had tested on ios 9.1 swift 2.0 xcode 7.1 if this works for you than please close issue.

**Comment by edwardIshaq** [comment]
im not clear how this got resolved? 
is it the notificationDelegate is nil and using listenEventsWithBlock instead ?
