### ISSUE TITLE
Use without status bar

### ISSUE THREAD

**Issue by delucamike** [AlvaroFranco/AFDropdownNotification#18]
What is the best way to adjust the code if you don't have the status bar visible in your app?  Currently the padding at the top assumes there is a status bar, so without one there is a bit of a gap.

**Comment by iop883684** [comment]
Find 20 in this method and replace to 0
-(void)presentInView:(UIView *)view withGravityAnimation:(BOOL)animation;
http://pastebin.com/NsWuTkQB
