### ISSUE TITLE
Replace delegate with blocks

### ISSUE THREAD

**Issue by loicgriffie** [AlvaroFranco/AFDropdownNotification#4]
Hi,

Very nice component. Would be very nice to replace the delegate method with blocks.

Regards,

**Comment by AlvaroFranco** [comment]
Working on it :)

**Comment by loicgriffie** [comment]
Can't wait for it ;)

**Comment by AlvaroFranco** [comment]
The v2 is currently on the works and is likely to be released really soon. This feature is included, of course
